### ISSUE TITLE
Handling WMS failure

### ISSUE THREAD

**Issue by maxfischer2781** [grid-control/grid-control#22]
It seems that the handling of WMS failing to retrieve a job has changed quite a bit. As a result, the HTCondor backend may produce an unneeded traceback:
```
2016-08-22 18:04:01 - wms.condor:ERROR - Job result file '/storage/a/akhmet/grid-control-workdir/SELECTION_DATA_CMSSW_7_6_5_patch1_CONDOR/sandbox/581/job.info' is empty
Traceback (most recent call last):
  File "/portal/ekpcms5/home/akhmet/CMSSW_7_6_5_patch1/src/grid-control/packages/grid_control/backends/wms.py", line 242, in retrieveJobs
    job_info = self._job_parser.process(pathName)
  File "/portal/ekpcms5/home/akhmet/CMSSW_7_6_5_patch1/src/grid-control/packages/grid_control/output_processor.py", line 44, in process
    raise JobResultError('Job result file %r is empty' % fn)
JobResultError: Job result file '/storage/a/akhmet/grid-control-workdir/SELECTION_DATA_CMSSW_7_6_5_patch1_CONDOR/sandbox/581/job.info' is empty
2016-08-22 18:04:01 - Job 581  state changed from DONE to FAILED  (error code: -1)
```
The way I see it, the condor WMS should validate the sandbox [at this point](https://github.com/grid-control/grid-control/blob/master/packages/grid_control/backends/condor_wms/condor_wms.py#L201) and return `sandpath` as `None` otherwise. Is there an API for validating the sandbox or should it be checked for any files/`job.info` in specific?

**Comment by FredStober** [comment]
The retrieveJobs (and the related _getJobsOutput) API hasn't changed *yet* - this will be part of the next backend refactoring patch. The checkJobs API *did* change, so it could be that previously these kinds of jobs were directly set to FAILED instead of DONE, so the retrieveJobs function was never called for these jobs. It would be best to really understand what is happening in these cases. The job obviously didn't write a job.info - which is quite strange in the first place ...

**Comment by maxfischer2781** [comment]
The underlying issue here is actually *HTCondor* failing the job. IIRC this happens if the job is broken (cannot transfer input etc.), the WN losses connection during output transfer, or the job never completed. 

Since the global `condor_q` only tells you that the job is gone, the condor backend marks **all** removed jobs as "done" and lets the rest of the pipeline figure out the actual status. This could be handled more cleanly with the new `checkJobs` API.

The htcondor backend was using the [`condor_q -userlog` option](https://github.com/grid-control/grid-control/blob/4fbed8169b6549175cfe145a0d170150c6ec457d/packages/grid_control/backends/htcondor_wms/htcondor_schedd.py#L330). This gives the actual exit status, and allows picking up WMS and job result separately.

**Comment by FredStober** [comment]
Note: There is an API for this now - [CheckStatus](https://github.com/grid-control/grid-control/blob/master/packages/grid_control/backends/aspect_status.py#L24)
It is currently used by the GridEngine and Condor backend (see 080914feeb594a402c1792cbce0652f8b17753b2)
